services:
  idp:
    build:
      context: ./idp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 3

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - EXTERNAL_API_BASE_URL=http://idp:8080
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      idp:
        condition: service_healthy
